# Generated by Django 2.2.28 on 2022-08-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190907_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='dev_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=100)),
                ('position1', models.CharField(choices=[('DevOps', 'Male'), ('Developer', 'Female'), ('Blogger', 'Male'), ('Youtuber', 'Female')], max_length=50)),
                ('position2', models.CharField(choices=[('DevOps', 'Male'), ('Developer', 'Female'), ('Blogger', 'Male'), ('Youtuber', 'Female')], max_length=50)),
                ('position3', models.CharField(choices=[('DevOps', 'Male'), ('Developer', 'Female'), ('Blogger', 'Male'), ('Youtuber', 'Female')], max_length=50)),
                ('position4', models.CharField(choices=[('DevOps', 'Male'), ('Developer', 'Female'), ('Blogger', 'Male'), ('Youtuber', 'Female')], max_length=50)),
                ('position5', models.CharField(choices=[('DevOps', 'Male'), ('Developer', 'Female'), ('Blogger', 'Male'), ('Youtuber', 'Female')], max_length=50)),
            ],
        ),
    ]
