# Generated by Django 2.2.28 on 2022-08-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_dev_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dev_profile',
            name='position5',
        ),
        migrations.AlterField(
            model_name='dev_profile',
            name='position1',
            field=models.CharField(blank=True, choices=[('DevOps', 'DevOps'), ('Developer', 'Developer'), ('Blogger', 'Blogger'), ('Youtuber', 'Youtuber')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dev_profile',
            name='position2',
            field=models.CharField(choices=[('DevOps', 'DevOps'), ('Developer', 'Developer'), ('Blogger', 'Blogger'), ('Youtuber', 'Youtuber')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dev_profile',
            name='position3',
            field=models.CharField(choices=[('DevOps', 'DevOps'), ('Developer', 'Developer'), ('Blogger', 'Blogger'), ('Youtuber', 'Youtuber')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dev_profile',
            name='position4',
            field=models.CharField(choices=[('DevOps', 'DevOps'), ('Developer', 'Developer'), ('Blogger', 'Blogger'), ('Youtuber', 'Youtuber')], max_length=50),
        ),
    ]
