# Generated by Django 2.2.13 on 2022-09-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220807_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev_profile',
            name='position1',
            field=models.CharField(blank=True, choices=[('DevOps', 'DevOps'), ('Developer', 'Developer'), ('Blogger', 'Blogger'), ('Youtuber', 'Youtuber')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='dev_profile',
            name='position2',
            field=models.CharField(blank=True, choices=[('DevOps', 'DevOps'), ('Developer', 'Developer'), ('Blogger', 'Blogger'), ('Youtuber', 'Youtuber')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='dev_profile',
            name='position3',
            field=models.CharField(blank=True, choices=[('DevOps', 'DevOps'), ('Developer', 'Developer'), ('Blogger', 'Blogger'), ('Youtuber', 'Youtuber')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='dev_profile',
            name='position4',
            field=models.CharField(blank=True, choices=[('DevOps', 'DevOps'), ('Developer', 'Developer'), ('Blogger', 'Blogger'), ('Youtuber', 'Youtuber')], default=1, max_length=50),
        ),
        migrations.CreateModel(
            name='PostSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('photo', models.ImageField(upload_to='category/')),
                ('about', models.TextField()),
                ('is_draft', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.AuthorProfile')),
            ],
        ),
    ]
