# Generated by Django 2.2.13 on 2022-09-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20220930_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whoareyou',
            name='resume',
        ),
    ]
