# Generated by Django 2.2.13 on 2022-09-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_remove_whoareyou_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='asmpe',
            field=models.FileField(default=0, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
